---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  armv7: ghcr.io/home-assistant/armv7-base-debian:bookworm
  armhf: ghcr.io/home-assistant/armhf-base-debian:bookworm
  i386: ghcr.io/home-assistant/i386-base-debian:bookworm

# codenotary:
#   base_image: codenotary@frenck.dev
#   signer: codenotary@frenck.dev
