mqtt:
  url: FIREBOARD2MQTT_CONFIG_MQTT_SERVERURL
  clientOptions:
    protocolVersion: FIREBOARD2MQTT_CONFIG_MQTT_PROTOCOL_VERSION
    username: FIREBOARD2MQTT_CONFIG_MQTT_USERNAME
    password: FIREBOARD2MQTT_CONFIG_MQTT_PASSWORD
  # discoveryTopic: FB2MQTT_MQTT_DISCOVERY_TOPIC
  # baseTopic: FB2MQTT_MQTT_BASE_TOPIC
  # clientIdPrefix: FB2MQTT_MQTT_CLIENTID_PREFIX
loglevel: FIREBOARD2MQTT_CONFIG_LOGLEVEL
prefixEntityNamesWithFireboardId: FIREBOARD2MQTT_CONFIG_HOMEASSISTANT_PREFIXNAMESWITHFBID
prefixEntityNamesWithFireboardName: FIREBOARD2MQTT_CONFIG_HOMEASSISTANT_PREFIXNAMESWITHFBNAME

fireboard:
  accountEmail: FIREBOARD2MQTT_CONFIG_FIREBOARDACCOUNT_EMAIL
  accountPassword: FIREBOARD2MQTT_CONFIG_FIREBOARDACCOUNT_PASSWORD