mqtt:
  url: "mqtt://localhost:1883"
  clientOptions:
    reconnectPeriod: 5000
    protocolVersion: 5
  discoveryTopic: homeassistant
  baseTopic: "fireboard2mqtt"
  clientIdPrefix: "fireboard2mqtt"

homeAssistantDiscovery: true
prefixEntityNamesWithFireboardName: false
prefixEntityNamesWithFireboardId: false
fireboard:
    accountEmail: someone@example.com
    accountPassword: somepass

loglevel: 'info'
